contact_links:
- name: "\u2728 About Common Voice"
  url: https://commonvoice.mozilla.org/about
  about: "Learn more about how Common Voice Project works and how you can contribute" 
- name: "\U0001F5E3 Join the Community Chat"
  url: https://chat.mozilla.org/#/room/#common-voice:mozilla.org 
  about: "If you have quick question or would like to connect with contributors, join our element chat"
