contact_links:
- name: "\Join the Community"
  url: https://chat.mozilla.org/#/room/#common-voice:mozilla.org 
  about: "If you have quick question or would like to connect with contributors, join our element chat"
  
